### ISSUE TITLE
Not found in the available plugins in Sublime Package Control.

### ISSUE THREAD

**Issue by politicus** [apiad/sublime-browser-integration#1]
Typed "browser" and didn't find it.

**Comment by apiad** [comment]
It wasn't merged a few hours ago, but it has been merged already.

**Comment by politicus** [comment]
I am sorry but I don't know what it does mean?
If you mean the plugin should be available now via Sublime Package Control, it isn't.

I tried a couple minutes ago.

**Comment by apiad** [comment]
You are right, it was merged, but I had a wrong tag name, so it appears on the website, but it is not available to install through the plugin yet. We'll have to wait until the crawler finds the new tag. I'll reopen the issue. Thanks again ;).

**Comment by politicus** [comment]
Thank you. New to Github ;-)

**Comment by apiad** [comment]
Well, it is working now...
